### ISSUE TITLE
Cuboid max 92 Watts

### ISSUE THREAD

**Issue by jram0421** [ClockSelect/myevic#105]
Hey, in power mode on the Cuboid, I'm only showing  a max of 92 watts, can you fix this?

**Comment by LordNex** [comment]
Strange. I'm not having that problem. Are you sure it's not your resistance of the coils in your atty?

On Oct 27, 2016, at 5:47 PM, jram0421 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey, in power mode on the Cuboid, I'm only showing a max of 92 watts, can you fix this?

##

**Comment by ClockSelect** [comment]
Your resistance must be 0.15 or 0.89 I guess?

It must be between 0.32 and 0.40 to have full access to the 200W

**Comment by LordNex** [comment]
Exactly. Every device has its "sweet point" per say that due to ohm law will allow it full access. This still is in effect for regulated mods.

On Oct 27, 2016, at 9:01 PM, ClockSelect <notifications@github.com<mailto:notifications@github.com>> wrote:

Your resistance must be 0.15 or 0.89 I guess?

It must be between 0.32 and 0.40 to have full access to the 200W

##

**Comment by afol2** [comment]
Guess is the AMP limit..... 25 amp limit

**Comment by ClockSelect** [comment]
Almost all boxes have a 9V/25A limit; only the triple-cells have a 50A limit.

**Comment by jram0421** [comment]
Gotcha. My coil is I think the .5 ohm SSOC from Kanger. So that would explain it. Thanks!
