### ISSUE TITLE
BVO settings - small glitch in settings

### ISSUE THREAD

**Issue by phantasm** [ClockSelect/myevic#138]
Changing BVO settings will only update voltage readings after the second click.
P.S.: its behavior seems to be more complex, but it still updates the readings inconsistently

Video: https://www.youtube.com/watch?v=yPmSnXruueE

Box Model: RX2/3

**Comment by ClockSelect** [comment]
That's because the voltage readings _are_ inconsistents in the first place.
Especially on RX boxes. Probed values may vary a bit randomly due to sampling noise.
You usually can't see it because the firmware uses thresholds to change displayed voltages, but in this menu you have unfiltered voltages displayed.

**Comment by ClockSelect** [comment]
I'll made a little tweak so things will be more clear.

**Comment by ClockSelect** [comment]
Now you'll have a better view of what's going on.
