### ISSUE TITLE
nice firmware, any plan to remove rom gaming to improve feature tx

### ISSUE THREAD

**Issue by zais1** [ClockSelect/myevic#148]
nice firmware, any plan to remove gaming rom to add space feature to improve feature tk
also : 
- can we have battery profile match for evicvtwo & evic basic tk
- wattage movement per 1 wattage / 0.5 w rather than 0.1 tk

**Comment by ClockSelect** [comment]
Things will be removed in a near future, indeed.
Game, SMART mode, glyphs...

For built-in batteries, I use Joyetech's curve since I don't know the true discharge curve of those batteries, and unless someone disassemble the box to benchmark the battery there's no way to know.

Unless you vape around 5W, I don't really see the point of small increments. Maybe replacing the 0.1 increment by 0.5 would make sense; the 0.1 is useless, imo. That's questionable.

**Comment by SEEKNDESTROY** [comment]
I'm all for removing useless features to make room for what really matters.

**Comment by zais1** [comment]
yes seems agreed take care

**Comment by phantasm** [comment]
@ClockSelect, maybe
if < 5W, use 0.5 step
if >= 5W, use 1.0 step, i.e.:
1.0W, 1.5W ........ 4.5W, 5W, 6W, 7W...

**Comment by ReMicroN** [comment]
Using <5W on 200W 3-battery boxmod?=)

**Comment by LockManipulator** [comment]
I love having flappy bird, maybe make it optional to put on? I would hate to lose it.

**Comment by ClockSelect** [comment]
@LockManipulator : A spare Nokia 1300 can be found for less than $10 nowadays.

**Comment by LockManipulator** [comment]
It's more of a "cool factor" for me to have it on my vape. If the general consensus is it should be removed for other features though, I can't argue. Is there a way I'd be able to put it back on myself in lieu of the other features?

**Comment by ClockSelect** [comment]
@LockManipulator : You can have your own fork of the project, if you wish, and keep/include whatever you want. But Flappy Bird is not gone yet.

**Comment by zais1** [comment]
does less rom gives better power longevity?

**Comment by ClockSelect** [comment]
@zais1 : no, it has no influence on power consumption.

**Comment by ClockSelect** [comment]
We'll come back later on this. I remember the power thing.
