### ISSUE TITLE
LOGO does not show up

### ISSUE THREAD

**Issue by ClockSelect** [ClockSelect/myevic#15]
LOGO is sometimes not displayed.
Under investigation.

**Comment by Daveee10** [comment]
It solved when flashing original firmware, reset dataflash, falsh myevic firmware...

**Comment by Daveee10** [comment]
Hmmm.... Logo turned off, some firing, power off/on, logo turned on and nothing... Logo not working...

**Comment by ClockSelect** [comment]
Yes, Logo works a few time then ceases working. Still not found why.

**Comment by Daveee10** [comment]
Ok, I make some test on VTC mini and Presa... Everytime when resetting dataflash the logo works... I'm tried power off, firing, power off, change some settings, flip display and everything and the logo works good... BUT after turn off the logo and back to on the logo never works... I think the problem is in the setting method... I check the code but don't find the problem...

**Comment by ClockSelect** [comment]
Idem.

**Comment by ClockSelect** [comment]
Fixed.

When you extract a bit from a bit field, the integer value is not 0 or 1 but 0 or ~0, which is quite different.
(~0 gives you -1 or MAX_UINT depending on the signess).
