### ISSUE TITLE
Compatibility for Elitar pipe?

### ISSUE THREAD

**Issue by AAI688** [ClockSelect/myevic#224]
**Box Model:**

is this firmware compatible with Joyetech Elitar Pipe? since it is a Joyetech product too.. however i can see the screen size is smaller so im not too sure if its okay to try or not. I would try if there is no chance of bricking it. Is there any chance of bricking?

Thanks in advance.

**Comment by donicrosby** [comment]
I don't think it will be supported probably for the same reason why the original rx200 isn't, the screen is not big enough. I wouldn't try flashing this to your device because it is not on the list of supported devices it will most likely brick it.

However if someone knows if it is possible to create another version of this firmware for the smaller screens it would allow those devices to be much better.

**Comment by TBXin** [comment]
Small screens is not problem, just requires some attention and time.
This CFW supports rx200, istick pico, istick100, etc.

![](http://i.imgur.com/A65TaMY.png)

Elitar has 64x32 display, and some new devices from Eleaf has same screen.

**Comment by AAI688** [comment]
is there a way to pull the current firmware from elitar also so that incase any f*ck ups it can be flash back to original?? joyetech website dont have the original firmware/flasher yet. which is one of the reasons why i havent flashed myevic/arcticfox firmware..

**Comment by TBXin** [comment]
Neither myEvic nor ArcticFox are not supporting Elitar, so, even if OFW will be available you still can't upload CFW to your Elitar.

P.S.
OFW - Original firmware
CFW - Custom firmware

**Comment by AAI688** [comment]
okay, i just wait for either to come out then.. which other new devices u said uses the elitar screen from eleaf btw? i cant seem to find any..

**Comment by TBXin** [comment]
http://www.eleafworld.com/aster-rt/
