### ISSUE TITLE
RX200s and 25R batt usb charging issue

### ISSUE THREAD

**Issue by userdsp** [ClockSelect/myevic#269]
One of my batteries was droped to 1.0 volts while mod was charged over usb! The wast one under the door. The other two batteries have 3.56v and 3,48v.

**Comment by TBXin** [comment]
Check your battery with voltmeter first.

**Comment by userdsp** [comment]
That was the first thing I did. The volmeter also showed 1 volt.

**Comment by ClockSelect** [comment]
What makes me suspicious is that if the firmware had such an issue I'd already have tons of issues opened on that subject since we have plenty of RX200S users.

Is the issue reproducible (without letting it go down to 1v - it'd kill the battery)? Do you actually see an unbabalance growing on the charge screen while charging via USB? And does the box work fine on this regard with the stock firmware?

**Comment by userdsp** [comment]
This issue was happened after flashing your previous firmware. I don't have the same  problem with the last one. All batteries had 3.5 volts before I start charge them. I hope this issue is stick to the previous firmware version! This is the first issue like this for me and I never have those problems before (with the stok firmware). I own this mod from 3 month's ago.
