### ISSUE TITLE
[Question] Porting

### ISSUE THREAD

**Issue by Dil3mm4** [ClockSelect/myevic#304]
Hello there, are there some guide/help lines to port this firmware to another device? 
Is there a proper documentation for devs about this firmware? 
Thank you for your time.

**Comment by fOmey** [comment]
I'm sure you have already but take a look at the commits for new devices, it will give you an idea what is involved. https://github.com/ClockSelect/myevic/commit/6bdf4b343d0a2cd678a9fc7f5ef84beba089af3b

I also have some questions about porting in devices.. would be great if @ClockSelect could do a write up.

**Comment by ClockSelect** [comment]
I can't, really. Any new device may have some surprises, and I burned some boxes learning it. I won't make a do-it-yourself doc for that, since I feel somewhat responsible for what I do and for for what people do with it. I won't provide a documentation that may not fit the next device about wich I know nothing.

**Comment by Dil3mm4** [comment]
That's clever.
And I really appreciate you for that. 
Can you take a look on my latest issue?
Would be nice to hear words from you. :)

**Comment by ClockSelect** [comment]
Are you talking about #337 ?
(please give a link when you talk about another issue)

**Comment by Dil3mm4** [comment]
Yes! :)

Il 30/ago/2017 04:35, "ClockSelect" <notifications@github.com> ha scritto:
