### ISSUE TITLE
RTC on 3rd info line 

### ISSUE THREAD

**Issue by marvinerzz** [ClockSelect/myevic#55]
the Real time clock on the 3rd info line gets stuck on displaying the time of last activity(like if you press a button at 00:00:00 it stays there until you press another button, and so on).

**Comment by ClockSelect** [comment]
I dot not have this problem; or maybe I didn't understand what you mean.
What I recently changed is about the PUFF counters (count & time), now you may reset them with a long fire click, and after that, they stay in editing mode (blinking) so that you still can change the 3rd line item. It makes it easier to reset both counters at once.
Also, the PUFF timer looks like a real time (PUFF 0:00:00) instead of (TIME 99999).
But nothing changed regarding the RTC.

**Comment by maelstrom2001** [comment]
The main screen must be refreshed periodically while displaying clock in 3rd line.
Adding `ScreenRefreshTimer = 5;` after drawing time procedure (in `case 7: // Real-time clock` of mainview.c) eliminates these "freezes".

**Comment by ClockSelect** [comment]
Wrong way^^
Clock moved from 6 to 7 some time ago and the function IsClockOnScreen() in screens.c has not been updated. The dfAPT == 6 should be a 7.
Will be fixed in next release.

**Comment by ClockSelect** [comment]
Should work.
