### ISSUE TITLE
VTC Mini - CLK Speed?

### ISSUE THREAD

**Issue by jaaxx** [ClockSelect/myevic#67]
The instructions say to use + & - to adjust the time at the top of the screen, but on my VTC mini it only adjusts the ratio on the center of the screen.  User error on my part?

**Comment by eVic75** [comment]
Do you mean: Menus > Clock > Clock Speed? I think you have old version of software.  Install newer/newest.

![2016 10 08 12 43 53](https://cloud.githubusercontent.com/assets/22393437/19212611/4379f398-8d55-11e6-81f9-9ca050544036.png)

**Comment by ClockSelect** [comment]
If you don't see the time changing on top by adjusting the ratio, it means your box did not sleep long enough the last time it slept. It may be due to the fact it slept a few seconds just before you entered the menu. When you wake up your box after some time and wish to adjust the ratio, it's important not to let it enter sleep mode again in-between.
