### ISSUE TITLE
Please confirm the Hardware version

### ISSUE THREAD

**Issue by batsteek** [ClockSelect/myevic#80]
No issues at all since the very beginning, and for the very last commit (f92ddb0d81fd60eb7c4f6ddaa5abfceb72054ce3) I get the following message when I try to update the box: Please confirm the Hardware version.

Any idea?

https://www.dropbox.com/s/gv0oqjyudiy2am3/Capture%20d%27%C3%A9cran%202016-10-15%2009.57.54.jpg?dl=0

**Comment by ClockSelect** [comment]
Yes; you lost the hardware version.
I happens when the updater fails to correctly rewrite the dataflash to reset the box during the update process. It's not related to the firmware version.

To recover it, you have to remember what was your hardware version; if not, you'll have to try starting with 1.00.

Follow the following guideline:
- With an utlity such as [NFirmwareEditor](https://github.com/TBXin/NFirmwareEditor/releases), download and save your dataflash to a file (if you're using NFE, it's in the Tools>Firmware Updater>Advanced Tab menu).
- With an HEX editor, remplace the first 8 bytes of the file by:  
  `00 00 00 00 64 00 00 00`  
  The "64" should be your hardware version number in hexadecimal:  
  1.00 : 64  
  1.01 : 65  
  1.02 : 66  
  etc...  
- Rewrite the file to your box with the utility.

It should work.

If if works but you have a scrambled screen, it just means you have the wrong hardware version. Retry with 1.01 or 1.02.

Btw, what's your box model?

**Comment by batsteek** [comment]
Thanks for the procedure. 
My box is an Evic VTC Mini, as for the hardware version, I don't remember so I'm going to try as per your explanations.

**Comment by batsteek** [comment]
mmm ...
1- Regarding the Hardware version, if it's lost, I still see it from the Update utility & NFE and it says 1.00.  Still you think it's lost?

![updater](https://www.dropbox.com/s/5jtf10jpu14cxyv/Capture%20d%27%C3%A9cran%202016-10-15%2016.05.03.jpg?dl=1)

![NFE1](https://www.dropbox.com/s/abzmjlllgfeq3eo/Capture%20d%27%C3%A9cran%202016-10-15%2016.19.21.jpg?dl=1)

As for NFE 5.1, when I try to read/save the dataflash, I get the following message: "An exception occured during dataflash reading. Operation timed out".

![NFE2](https://www.dropbox.com/s/g7af1fwwe6w4y0w/Capture%20d%27%C3%A9cran%202016-10-15%2016.12.43.jpg?dl=1)

Note: It's a Windows 10 on a Parallels Virtual Machine on my MAC. (and I never got any issues until today.)

**Comment by batsteek** [comment]
Don't know why/how, but I finally managed to grab the dataflash and ... I see the hardware version (64) so ... I don't know what to do now ...

![dataflash](https://www.dropbox.com/s/9aaneojohifsh4n/Capture%20d%27%C3%A9cran%202016-10-15%2017.54.18.jpg?dl=1)

**Comment by slavyk** [comment]
Maybe this help you [https://github.com/ClockSelect/myevic/issues/2#issuecomment-240336605](url)

**Comment by slavyk** [comment]
Maybe this help you [https://github.com/ClockSelect/myevic/issues/2#issuecomment-240336605](url)

**Comment by slavyk** [comment]
Maybe this comment can help you [https://github.com/ClockSelect/myevic/issues/2#issuecomment-240336605](https://github.com/ClockSelect/myevic/issues/2#issuecomment-240336605)

**Comment by batsteek** [comment]
thanks @slavyk 

Okay okay!
Issue with my box is only with the last commit (f92ddb0d81fd60eb7c4f6ddaa5abfceb72054ce3)

> [#16][#72] Force X32 OFF on non-RTC boxes.
> This will prevent some boxes from freezing at startup or firmware upgrade failures.

I tried the previous one without any issue.

I hope it will help you :)

**Comment by ClockSelect** [comment]
I see you have the NFE option ON. Set if to OFF when updating firmwares (in the Expert menu). It's the cause of your issue.

Problem is not your hardware version, it's not lost. It would show 0.00 otherwise.

In previous firmware versions, I set the NFE option to ON by default, but it appear it was a mistake.

**Comment by batsteek** [comment]
Yep, this is what I do.
It was enabled only because I was dealing with NFE at the moment of the screenshot so (I guess) it's not the reason of my issue.

**Comment by ClockSelect** [comment]
Found the issue.
Working on it.

**Comment by ClockSelect** [comment]
gcc compiler "optimized" product IDs in the code by computing some from the others, so some boxes ID didn't appear any more in the binary file.

**Comment by batsteek** [comment]
Still the same initial issue with the last commit ebac1b596ddc38f957d766d6878939a2a9eca667
-> Please confirm the Hardware version.

**Comment by Hotix71** [comment]
ebac1b5 working for me with VTC, thanks!

Iam using NFE for the update....

**Comment by ClockSelect** [comment]
Seems there's still an issue with official updater.
But NFE works.

**Comment by ClockSelect** [comment]
Should work fine now.
Seems that some updaters want the product ID to be aligned on a 32-bits boundary.

**Comment by batsteek** [comment]
And yes, it works now :)
Thanks for such a cool work!
