### ISSUE TITLE
Decrease highest step speed

### ISSUE THREAD

**Issue by fonix232** [ClockSelect/myevic#86]
The highest step speed seems to be WAY too fast compared to the slower steps. It would be nice if this could be changed, or decreased by default.

**Comment by Nestorfish** [comment]
I disabled the last speed, it was way too fast for me too.

**Comment by ClockSelect** [comment]
With the options to increase by + or -1 Watt, this shouldn't be a concern any more.
The terminal velocity is reached after more than 5 seconds pressing the button. This just means "go all the way up".

**Comment by ClockSelect** [comment]
Problem arise when dealing with high-power boxes. When you have to go through 30 to 75, it's rather easy to do with a reasonable speed. But soon, we'll have to go from say 30 to 250, and it's no longer easy to deal with. We don't know where people want to stop when they start to press the button. There is no universal solution. Ideas welcome.

**Comment by t2dYuri** [comment]
Maybe some initial check with condition like:
if([max.wattage] <= 80) {
  use [slow-speed-rotation method];
} else {
  use [high-speed-rotation method];
}

and it would be nice if the user could choose step by 0.5 Watt (besides 0.1 & 1.0) - it's for low-wattage-vapers, who runs their boxes at 10-30 watts, where +-0.5W can be felt?
Thank you.

**Comment by fonix232** [comment]
I understand the need for higher speeds, however the overall menu stepping speeds are not distributed in a balanced way.

Say I want to get from the default 20W to 80-90W. I start pressing +, number starts to roll, and in 5 seconds it reaches approx. 35W. After that it begins to spin out of control and needs VERY precise timing to hit near the wanted value.

So either increase the speed of the second fastest stepping, or decrease the speed of the fastest, which would allow for more precision.

In my experience manufacturers got this bit quite right in the stock firmwares, so maybe a device-specific stepping speed implementation would help? Say, a simple switch:

```
switch(currentDevice) {
    case CUBOID:
        speed1 = CUBOID.speed1;
        speed2 = CUBOID.speed2;
        speed3 = CUBOID.speed3;
        break;
    case RX75:
    case [...]:
        break;
    default:
        // set default 
        break;
```

**Comment by ClockSelect** [comment]
I don't want to make complicated things.
The way OFW handle speeds is bad, obviously; I prefear the eleaf way.
I'll try things.
If you find a box do it well, tell me wich.

**Comment by dabugen** [comment]
Honestly, I like the speeds how they are right now in your firmware.

**Comment by Nestorfish** [comment]
All this may be due to the way the speed change, and not the maximum speed itself.
I tried a progressive ramp:
https://github.com/Nestorfish/myevic/commit/4575eb44b8b63fc4d093970f879b4063ac974e35
It prevents speed jumps accross sections, reaching the "1W" step at 1W/s after 4.6 seconds, then progressively going to 10W/s for another 3.6 seconds. Maybe this last step can be made a little shorter.

**Comment by ClockSelect** [comment]
@Nestorfish: seems fine like this - need some practice to get used to it but eh.

**Comment by Nestorfish** [comment]
There is a little glitch at the change between 5 and 100Hz. For example, if you start from 10W, you won't see 10.6W (at least my eyes don't ;)).
When you enter the bloc with KeyTicks = 4, you will leave with KeyTicks = 5, and KRDelay will be decremented at 100Hz rate. This one being 0, KeyTicks = 5 will last for only 10ms instead of the wanted 200ms.
Given that you compute KRDelay to delay the next KeyTicks value event, I think it would be clearer to update KeyTicks before computing KRDelay.

**Comment by ClockSelect** [comment]
That's right; didn't even notice.
I'll have a look.
